- hosts: SAN
  become: yes
  become_user: root
  ignore_errors: yes
  serial: 10
  gather_facts: no
  tasks:
  - name: Extending the disk
    shell: lvextend -L +45G /dev/mapper/omsvg-lvapp

  - name: Resizing the File System
    shell: xfs_growfs /dev/mapper/omsvg-lvapp
