- hosts: localhost
  gather_facts: no
  ignore_errors: yes
  vars_files:
    - /home/s_snalam/ANSIBLE/Password/CTE/playbooks/cte_pwd.yml
  tasks:
  - name: Updating  Password in Hashicorp Vault
    uri:
        url: http://vault1.va.star.com/v1/CTE/CH
        headers:
            Authorization: "Bearer s.Awp2XwFQ6yzXLGFnCOBaC77G"
        method: POST
        body:
             password: 13bifwgugwocwcw
        body_format: json
        return_content: true
        status_code: 204
